import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "1440"))

PREDICTION_LOCK_MINUTES_BEFORE_KICKOFF = int(
    os.getenv("PREDICTION_LOCK_MINUTES_BEFORE_KICKOFF", "30")
)

PREDICTION_REMINDER_MINUTES_BEFORE_KICKOFF = int(
    os.getenv("PREDICTION_REMINDER_MINUTES_BEFORE_KICKOFF", "120")
)

AGENDA_REMINDER_MINUTES_BEFORE_KICKOFF = int(
    os.getenv("AGENDA_REMINDER_MINUTES_BEFORE_KICKOFF", "60")
)

MATCHES_PROVIDER_URL = os.getenv("MATCHES_PROVIDER_URL", "")

PAYMENT_PROVIDER = os.getenv("PAYMENT_PROVIDER", "mock")

NOTIFICATIONS_ENABLED = os.getenv("NOTIFICATIONS_ENABLED", "true").lower() == "true"

MAX_TICKET_RESERVATIONS_PER_DAY = int(
    os.getenv("MAX_TICKET_RESERVATIONS_PER_DAY", "5")
)

MAX_TICKET_TRANSFERS_PER_DAY = int(
    os.getenv("MAX_TICKET_TRANSFERS_PER_DAY", "3")
)

MAX_TICKET_REFUNDS_PER_DAY = int(
    os.getenv("MAX_TICKET_REFUNDS_PER_DAY", "3")
)

ANTIFRAUD_WINDOW_HOURS = int(
    os.getenv("ANTIFRAUD_WINDOW_HOURS", "24")
)

FRAUD_AUTO_SUSPEND_THRESHOLD = int(
    os.getenv("FRAUD_AUTO_SUSPEND_THRESHOLD", "10")
)