sonar.projectKey=smahechar_MUNDIALITO2026_HUB
sonar.organization=smahechar

sonar.projectName=Mundialito2026 Hub
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Código fuente principal
sonar.sources=src,backend

# Archivos de prueba
sonar.tests=src,backend/tests

# Pruebas que debe reconocer SonarCloud
sonar.test.inclusions=backend/tests/**/*.py,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

# Exclusiones generales
sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/*.pyc,backend/manual_api_check.py,backend/test_api.py,backend/seeds/**,backend/venv/**

# Exclusiones de cobertura
sonar.coverage.exclusions=backend/tests/**,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx,backend/seeds/**,backend/manual_api_check.py,backend/test_api.py

# Versiones / lenguajes
sonar.python.version=3.11

# Reportes de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml